[Interface]
# Key for Proxy India
# Bouncing = 10
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = UGOrXkbGmT/QazcWgR40vhIsePbIK8R3RyZqloZ29VA=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# IN#23
PublicKey = QnqJI0C2xQZrKfZLrBaCHa2h3TZ9CBt6sCuzg3ue4X4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.142.18:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:2:1::10]:51820
PersistentKeepalive = 25