[Interface]
# Key for Proxy US
# Bouncing = 12
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = EEtvP0CrfW0i92iDyAwldTtVW6JxSO19Jl+z79Ylt2k=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# US-MA#128
PublicKey = ePaJ2vLb/+bIbE+V7DD2DHyLqX9FsbKwHP4XTyPv4GU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 62.93.176.129:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:f911:6589::10]:51820
PersistentKeepalive = 25