services:
  beszel:
    image: docker.io/henrygd/beszel:latest
    container_name: beszel
    ports:
      - "8090:8090"
    volumes:
      - ./beszel_data:/beszel_data:Z
    restart: unless-stopped

  beszel-agent-podman:
    image: docker.io/henrygd/beszel-agent:latest
    container_name: beszel-agent-podman
    user: "1000"
    network_mode: host
    environment:
      - KEY=${BESZEL_PODMAN_KEY}
      - TOKEN=${BESZEL_PODMAN_TOKEN}
      - HUB_URL=http://127.0.0.1:8090
      - DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
      - LISTEN=45876
    volumes:
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    restart: unless-stopped